# Generated by sgb2ns, created by Polly Huang
# GRAPH (#nodes #edges id uu vv ww xx yy zz):
# 10 44 geo(0,{10,10,3,0.300,0.000,0.000}) 10 

proc create-topology {nsns node linkBW} {
	upvar $node n
	upvar $nsns ns

	set verbose 1

	if {$verbose} { 
		puts "creating nodes..." 
}
		for {set i 0} {$i < 10} {incr i} {
			set n($i) [$ns node]
	}

	# EDGES (from-node to-node length a b):
	if {$verbose} { 
		puts -nonewline "Creating links 0..."
		flush stdout 
	}
	$ns duplex-link $n(0) $n(9) $linkBW 40ms DropTail
	$ns duplex-link $n(0) $n(6) $linkBW 60ms DropTail
	$ns duplex-link $n(0) $n(5) $linkBW 30ms DropTail
	$ns duplex-link $n(0) $n(2) $linkBW 40ms DropTail
	$ns duplex-link $n(0) $n(1) $linkBW 20ms DropTail
	$ns duplex-link $n(1) $n(3) $linkBW 40ms DropTail
	$ns duplex-link $n(2) $n(9) $linkBW 30ms DropTail
	$ns duplex-link $n(2) $n(8) $linkBW 90ms DropTail
	$ns duplex-link $n(2) $n(7) $linkBW 90ms DropTail
	$ns duplex-link $n(2) $n(6) $linkBW 30ms DropTail
	if {$verbose} { puts -nonewline "10..."; flush stdout }
	$ns duplex-link $n(2) $n(4) $linkBW 60ms DropTail
	$ns duplex-link $n(3) $n(9) $linkBW 40ms DropTail
	$ns duplex-link $n(3) $n(8) $linkBW 50ms DropTail
	$ns duplex-link $n(3) $n(4) $linkBW 80ms DropTail
	$ns duplex-link $n(4) $n(9) $linkBW 40ms DropTail
	$ns duplex-link $n(4) $n(7) $linkBW 90ms DropTail
	$ns duplex-link $n(4) $n(5) $linkBW 100ms DropTail
	$ns duplex-link $n(5) $n(9) $linkBW 60ms DropTail
	$ns duplex-link $n(5) $n(7) $linkBW 40ms DropTail
	$ns duplex-link $n(6) $n(7) $linkBW 80ms DropTail
	if {$verbose} { puts -nonewline "20..."; flush stdout }
	$ns duplex-link $n(7) $n(9) $linkBW 70ms DropTail
	$ns duplex-link $n(8) $n(9) $linkBW 70ms DropTail

	if {$verbose} { 
		puts -nonewline "22..."
		flush stdout
		puts "starting"
	}
	return 10}
